googleapis/gax-ruby

lib/google/gax/api_callable.rb
Currently it retries if the error doesn't have 'code' attribute,
but that's not right, should raise errors for unexpected failures.
=> Fix the condition of retryable errors

lib/google/gax.rb, lib/google/gax/api_callable.rb, lib/google/gax/grpc.rb
This happened because gax-ruby originally borrowed the logic
and documentation string from gax-python -- some things are
not very ruby-ish.
- remove underscore-prefixed names: this is simply Pythonic
style but not necessary in Ruby. They are already marked
as private in the code.
- fix comments, mostly s/None/nil/
This fixes #15
=> Fix some wierd styles

lib/google/gax.rb, lib/google/gax/api_callable.rb, lib/google/gax/version.rb, spec/google/gax/api_callable_spec.rb
- Retire is_page_streaming call options, we don't use this anymore.
- Introduce page_token as a call option. This is similar to python
implementation.
- Unlike Python, Ruby provides per-page iteration as with another
method 'each_page'. I believe this is still good for Ruby users.
- Added example comments and a few fields for better usability
of PagedEnumerable. I hope this helps.
- related with #18.
=> Update page-streaming call options

lib/google/gax.rb, lib/google/gax/api_callable.rb, lib/google/gax/settings.rb, spec/google/gax/api_callable_spec.rb, spec/google/gax/settings_spec.rb
https://github.com/googleapis/gax-ruby/issues/26.
In this commit, errors are not treated as overridable.
=> Removed the grpc dependency from api_callable.

lib/google/gax.rb
The existing code fails with actual bundling configurations,
because construct_settings wants to set the field named as
delay_threshold_millis.
This _millis suffix also matches the style with BackoffSettings,
thus this is probably better.
=> Rename delay_threshold by delay_threshold_millis.

lib/google/gax/api_callable.rb, spec/google/gax/api_callable_spec.rb
I've noticed that timeout parameter is gone in 0.15.0 -- grpc assumes
'deadline' instead. Since deadline is in grpc-0.14.1, better to
stick with deadline argument.
=> Replace timeout by deadline.

.rubocop_todo.yml, lib/google/gax/api_callable.rb, lib/google/gax/version.rb, spec/google/gax/api_callable_spec.rb
gRPC 0.15.0 actually assumes metadata: argument rather than kwargs.
=> Use metadata argument

google-gax.gemspec, lib/google/gax/version.rb
Previous 0.15.0 causes version inconsistency with gcloud-ruby.
=> Update gRPC dependency on 1.0.0.pre1

lib/google/gax.rb, lib/google/gax/bundling.rb, spec/google/gax/api_callable_spec.rb
In Ruby, a 'private constant' is a constant which will have
to be accessed without prefix. So all entties inside of
Google::Gax can still access it as-is, but outside the module
it can't be accessed as Google::Gax::CallSettings.
This affects the tests, so this patch introduced a renaming
to toplevel ::CallSettings in a way to avoid violating
access of private constant.
updates https://github.com/googleapis/gax-python/issues/112
=> Hide CallSettings as private.

lib/google/gax.rb, lib/google/gax/version.rb, spec/google/gax/api_callable_spec.rb
See https://github.com/googleapis/toolkit/issues/446
=> Exclude loading grpc when require 'google/gax'.

lib/google/gax/version.rb
0.5.1 is already pushed to rubygems.org, for the fix of the file
permissions.
=> Update to 0.5.1

lib/google/gax/operation.rb, spec/google/gax/operation_spec.rb
Previously I thought it would be a clever idea to unpack the operation result and metadata based on the `type_url` found in the `google.protobuf.Any` message. Toolkit has been updated to have the api producer explicitly specify the expected types of the result and metadata. Since these types are explicitly specified by the api producer, these should be the only types unpacked from the operations.
This resulted in having the result and metadata types specified in the constructor of the `Google::Gax::Operation` rather than being dynamically found in the `type_url` of the `google.protobuf.Any` message or being specified by the user when the results or metadata messages are called.
=> Updates to LROs unpacking strategy.

.rubocop_todo.yml
Rubocop on CI is giving different results than my local machine. This is just a temporary fix until I figure out what causing the errors.
=> Silencing Rubocop

google-gax.gemspec, lib/google/gax/operation.rb, lib/google/gax/version.rb, spec/google/gax/operation_spec.rb
Add the following methods to `Google::Gax::Operation`:
* `#name`
* `#error`
* `#response?`
* `#response`
* `#delete`
=> Add Operation methods

lib/google/longrunning/operations_client.rb
Uses generated ruby version here: https://github.com/googleapis/googleapis/blob/master/gapic/packaging/api_defaults.yaml#L35
=> Update LRO headers to use generated ruby version.

.rubocop_todo.yml, lib/google/gax.rb, lib/google/gax/credentials.rb, lib/google/gax/grpc.rb, lib/google/gax/version.rb, spec/google/gax/credentials_spec.rb, spec/google/gax/grpc_spec.rb
Updates: https://github.com/googleapis/toolkit/issues/1324
- added `:updater_proc` as a delegated method
- removed default gcloud paths since they don't make sense in the google-gax context
- changed the test file to use rspec instead of minitest
=> Port credentials class from google-cloud-core

lib/google/gax/version.rb, lib/google/longrunning/operations_client.rb
This is a workaround to ensure backward-compatibility with older GAPIC
clients. It will be removed in GAX 0.9.0.
=> Set default scope for LRO client

lib/google/gax/errors.rb, lib/google/gax/grpc.rb, spec/google/gax/grpc_spec.rb
The details attribute provides easy access to deserialized error
details. Previously, API custom error types were only accessible
by inspecting the gRPC error, and then only availabe in serialized
form.
Fixes
https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1438
=> Add GAX error details attribute

lib/google/gax/grpc.rb, lib/google/gax/util.rb, lib/google/gax/version.rb, spec/google/gax/grpc_spec.rb, spec/google/gax/util_spec.rb
- Disables error detail deserialization until a fix in gRPC is released.
- Allows instances of proto messages to be passed to to_proto
- Bump version. Note that non-sequential increase is due to rollbacks
=> GAX bug fixes

google-gax.gemspec, lib/google/gax/version.rb
Previously, GAX depended on features only introduced in gRPC `1.6.2` and `1.6.6`.
=> Specify correct gRPC dependency

lib/google/gax/version.rb, lib/google/longrunning/operations_client.rb
The "correct" fix for this will be to have GAPICs that rely on LRO
override the service path attribute, rather than passing it in to
the constructor. But we need to continue supporting the constructor
argument without warning until that can be done.
Fixes #102
=> Remove warning from service port.

lib/google/gax/errors.rb, spec/google/gax/error_spec.rb
This PR relays the underlying BadStatus values `code`, `details`, and `metadata` without resorting to dynamic hackery using `method_missing`. If the underlying error object does not have values, or is not a BadStatus, `nil` is returned.
[refs GoogleCloudPlatform/google-cloud-ruby#1791]
[refs GoogleCloudPlatform/google-cloud-ruby#1825]
=> GaxError presents BadStatus values

lib/google/gax/api_callable.rb, spec/google/gax/api_callable_spec.rb
To be used to add routing headers like this:
```ruby
@create_book = Google::Gax.create_api_call(
@library_service_stub.method(:create_book),
defaults["create_book"],
params_extractor: proc do |request|
{'name' => request.name, 'book.read' => request.book.read}
end
)
```
=> Add request header params

lib/google/gax/version.rb, lib/google/longrunning/operations_client.rb
Note: this is hand-edited for now to preserve compatibility with older
GAPIC clients that set the service address through the ctor. We will
refresh the LRO codegen entirely for the 1.0 release.
=> Allow operations client to be subclassed

.rubocop.yml, .rubocop_todo.yml, lib/google/gax/api_callable.rb, lib/google/gax/errors.rb, lib/google/gax/grpc.rb, lib/google/gax/operation.rb, lib/google/gax/path_template.rb, lib/google/gax/util.rb, spec/google/gax/api_callable_spec.rb, spec/google/gax/bundling_spec.rb, spec/google/gax/error_spec.rb
This change allows GAX to raise more specific subclasses of GaxError
depending on the actual status of the call when the error is raised.
Fixes #100.
=> Create Errors subclasses analogous to google-cloud-core

.rubocop_todo.yml, lib/google/gax/api_callable.rb, lib/google/gax/settings.rb, spec/google/gax/api_callable_spec.rb, spec/google/gax/settings_spec.rb
This is a WIP for a potential new toolkit feature. The main goal is to invoke all internal grpc calls using the return_op=true flag so that any additional grpc information is available and can be trapped in gax, via an optional block. Those blocks will then be used by the generated gapic methods to trap and expose things like response metadata to the caller.
Related toolkit change: https://github.com/googleapis/toolkit/pull/1865
Note: Do not merge until the feature is finalized!
=> Update metadata handling and add block to expose grpc ops internally

CHANGELOG.md, RELEASING.md
We need to publish an update for GAX and I noticed that there is no documentation (#61). 
Can you do a quick sanity check or suggest improvements? I'll update as needed when I do an actual release os this is just a starting point (taken from the google-cloud-ruby).
=> Add release guide and changelog

CHANGELOG.md, lib/google/gax/version.rb
It seems this requires a review, unlike in google-cloud-ruby
=> Release google-gax v1.1.0

lib/google/longrunning/operations_client.rb
Google::Auth::Credentials initialization expects `scope`, not `scopes` as an option.
=> Fix scope option

.rubocop.yml, lib/google/gax/bundling.rb, lib/google/gax/operation.rb, spec/google/gax/operation_spec.rb
This PR changes `Google::Gax::Operation` to lookup the result and metadata types used to unpack the values from the `Google::LongRunning::Operation` object. This only happens when the `result_type` or `metadata_type` values are passed in as `nil` (which currently results in an error).
This change will enable the GAPIC client objects to retrieving operations through a `get_operation` and a `list_operation` method without having to know the specific result and metadata types to set. There are several APIs that have operation collections which contain resources with varied result and metadata types. Each `Google::LongRunning::Operation` object would have to be inspected and the result and metadata types discovered before passing to `Google::Gax::Operation.new`. This PR moves the result and …
=> Lookup Operation types to unpack

lib/google/gax/grpc.rb, spec/google/gax/grpc_spec.rb
This library attempts to automatically `unpack` the error messages details field (an `Any` proto) when an RPC fails. This was originally implemented by reconstructing the expected Ruby class name from the `type_name` property of the `Any` object. 
This change replaces that by `unpack` ing the object using the generated descriptor pool instead. A `ruby_namespace` option was added to protobuf around version 3.6, which makes the original implementation unreliable when used.
=> Use descriptor pool for deserialization

lib/google/gax/operation.rb, spec/google/gax/operation_spec.rb
This PR changes the `Google::Gax::Operation` `result_type` and `metadata_type` arguments to be optional. This is a backwards compatible change.
=> Make Operation class type arguments optional

google-gax.gemspec
Allow the dependency to use the 0.7.x releases.
=> Update googleauth dependency

google-gax.gemspec
Loosen the googleauth dependency to allow future changes. The team supporting googleauth has committed to not change backwards compatibility before 0.10.0.
=> Loosen googleauth dependency

.travis.yml, Gemfile
* Add workaround for using google-protobuf on ruby < 2.3.
* Add Ruby 2.6 to CI
=> Fix CI build and add Ruby 2.6 to CI

lib/google/gax/version.rb
We want to indicate that the master branch is not compatible with the current release, so use 2.0. But, we don't want it released, so append alpha and development to the version number to make that as obvious as possible.
=> Update version to 2.0.alpha.0.development

lib/google/gax/paged_enumerable.rb
Bug fix for calling ApiCall in PagedEnumerable. Oops.
This is a prerequisite for googleapis/gapic-generator-ruby#119.
=> Fix PagedEnumerable use of ApiCall#call

Rakefile, google-gax.gemspec, lib/google/gax/operation.rb, lib/google/gax/paged_enumerable.rb, test/google/gax/operation_test.rb
Use the new `Operations` class from gapic generator. Update the constructor to use named arguments for optional arguments (`result_type` and `metadata_type`).
=> Operation Updates

CHANGELOG.md, lib/google/gax/version.rb
gax doesn't use the usual release tools and needs to be released manually.
=> Update version and changelog for 1.7.1
